services:
  satisfactory:
    image: bitsfitr/satisfactory:latest
    restart: always
    ports:
      - "15777:15777/udp"
      - "15000:15000/udp"
      - "7777:7777/udp"
    volumes:
      - ./game:/home/steam/SatisfactoryDedicatedServer
      - ./.config:/home/steam/.config
      - ./Steam:/home/steam/Steam
      - ./.local:/home/steam/.local
